"""
ApexQuantum | Qiskit Circuit Transpiler & OpenQASM Exporter
============================================================
Translates interactive ApexQuantum web circuits into IBM Qiskit
and OpenQASM 2.0/3.0 formats for execution on real quantum hardware.

Author: Tareq Ali (@Tareq0001)
"""

import json
from typing import Dict, List, Optional


class QuantumCircuitTranspiler:
    """Transpiles ApexQuantum grid circuits into IBM Qiskit and OpenQASM."""

    def __init__(self, num_qubits: int = 4, num_steps: int = 8):
        self.num_qubits = num_qubits
        self.num_steps = num_steps

    def to_qiskit_code(self, circuit_grid: List[List[Optional[str]]]) -> str:
        """Converts a 2D circuit grid into runnable Python Qiskit code."""
        lines = [
            "# Generated by ApexQuantum Transpiler",
            "from qiskit import QuantumCircuit, transpile",
            "from qiskit_aer import AerSimulator",
            "from qiskit.visualization import plot_histogram, plot_bloch_multivector",
            "import matplotlib.pyplot as plt",
            "",
            f"qc = QuantumCircuit({self.num_qubits}, {self.num_qubits})",
            "",
        ]

        for step in range(self.num_steps):
            for q in range(self.num_qubits):
                gate = circuit_grid[q][step]
                if not gate:
                    continue

                if gate == "H":
                    lines.append(f"qc.h({q})")
                elif gate == "X":
                    lines.append(f"qc.x({q})")
                elif gate == "Y":
                    lines.append(f"qc.y({q})")
                elif gate == "Z":
                    lines.append(f"qc.z({q})")
                elif gate == "S":
                    lines.append(f"qc.s({q})")
                elif gate == "T":
                    lines.append(f"qc.t({q})")
                elif gate == "CX":
                    target_q = (q + 1) % self.num_qubits
                    lines.append(f"qc.cx({q}, {target_q})")
                elif gate == "M":
                    lines.append(f"qc.measure({q}, {q})")

        lines.extend([
            "",
            "# Execute simulation",
            "simulator = AerSimulator()",
            "compiled_circuit = transpile(qc, simulator)",
            "job = simulator.run(compiled_circuit, shots=1024)",
            "result = job.result()",
            "counts = result.get_counts(compiled_circuit)",
            "print('Measurement Counts:', counts)",
            "qc.draw(output='text')",
        ])

        return "\n".join(lines)

    def to_openqasm(self, circuit_grid: List[List[Optional[str]]]) -> str:
        """Exports the circuit into standard OpenQASM 2.0 format."""
        qasm = [
            'OPENQASM 2.0;',
            'include "qelib1.inc";',
            f'qreg q[{self.num_qubits}];',
            f'creg c[{self.num_qubits}];',
        ]

        for step in range(self.num_steps):
            for q in range(self.num_qubits):
                gate = circuit_grid[q][step]
                if not gate:
                    continue
                gate_lower = gate.lower()
                if gate == "CX":
                    target_q = (q + 1) % self.num_qubits
                    qasm.append(f"cx q[{q}], q[{target_q}];")
                elif gate == "M":
                    qasm.append(f"measure q[{q}] -> c[{q}];")
                else:
                    qasm.append(f"{gate_lower} q[{q}];")

        return "\n".join(qasm)


if __name__ == "__main__":
    # Example: Bell State (|Phi+>)
    demo_grid = [[None] * 8 for _ in range(4)]
    demo_grid[0][0] = "H"
    demo_grid[0][1] = "CX"

    transpiler = QuantumCircuitTranspiler()
    print("=== IBM QISKIT CODE ===")
    print(transpiler.to_qiskit_code(demo_grid))
    print("\n=== OPENQASM 2.0 ===")
    print(transpiler.to_openqasm(demo_grid))
